[project]
name = "pit"
version = "1.0.0"
description = "Pit significa 'Python Information Tracker'. Git-alike, hecho en Python"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.4",
]
