exclude = [
    "__pypackages__",
    "__pycache__",
    ".venv",
    ".vscode",
    ".git",
    ".github",


]

line-length = 100
indent-width = 4
target-version = "py313"

[lint]
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
